<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net4.6.2</TargetFramework>
        <UseWPF>true</UseWPF>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <RootNamespace>PlayGif</RootNamespace>
        <AssemblyName>PlayGif</AssemblyName>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DebugType>portable</DebugType>
        <PlatformTarget>AnyCPU</PlatformTarget>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DebugType>portable</DebugType>
        <PlatformTarget>AnyCPU</PlatformTarget>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="PlayniteSDK" Version="6.16.0.0" PrivateAssets="none" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
        <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3124.44" />
        <PackageReference Include="HtmlAgilityPack" Version="1.11.72" />
        <PackageReference Include="System.ValueTuple" Version="4.5.0" />
        <PackageReference Include="XamlAnimatedGif" Version="2.3.1" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="System.Net.Http" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\shell.html" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\extension.yaml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Include="..\icon.png" Condition="Exists('..\icon.png')">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Include="..\LICENSE" Condition="Exists('..\LICENSE')">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Include="..\THIRD-PARTY-NOTICES" Condition="Exists('..\THIRD-PARTY-NOTICES')">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
